language: node_js
node_js:
  - 8
install:
  - npm install -g gulp
  - ./setup.sh
script:
  - gulp lint --travis
  - npm test
before_deploy:
  - cp test/index.html dist/index.html
  - cp test/test-runner.js dist/test-runner.js
  - cp -r test/sample_data/ dist/sample_data/
  - cp -r test/static/ dist/static/
deploy:
  provider: pages
  local_dir: dist
  skip_cleanup: true
  github_token: $GITHUB_GHPAGES_TOKEN
  on:
    branch: master
