codecov:
  branch: main
  notify:
    require_ci_to_pass: no

comment: off

coverage:
  status:
    project:
      frontend:
        threshold: 0.02%
        flags: frontend
        if_not_found: success  # no commit found? still set a success
    patch:
      default:
        target: 100%

flags:
  frontend:
    paths:
      - src/js/**/*.js
